/**
 * Types for the Handover Checklist System
 */

// ==================== New Enums for Phase-based Checkout ====================

// Item types - determines which phase handles the item
// Note: ai_confirmation was removed - Phase 3 now always runs as final AI review
export type ItemType = "checkbox" | "numeric" | "text" | "selection" | "photo";

// Numeric validation types
export type NumericValidationType = "max" | "min" | "range" | "exact" | "tolerance";

// Session status - tracks which phase the session is in
export type SessionStatus =
  | "draft"
  | "phase1"
  | "phase2"
  | "phase3"
  | "pending_review"
  | "completed"
  | "abandoned";

// NG (problem) item status
export type NGStatus = "unresolved" | "in_progress" | "resolved";

// ==================== Legacy Types (kept for backward compatibility) ====================

// Priority levels
export type Priority = "P0" | "P1" | "P2" | "P3";

// Check item status
export type CheckItemStatus = "pending" | "done" | "blocked" | "na";

// Categories
export type Category = "safety" | "equipment" | "task" | "handover" | "other";

// ==================== New Models for Phase-based Checkout ====================

// Numeric validation settings
export interface NumericValidation {
  validation_type: NumericValidationType;
  min_value?: number;
  max_value?: number;
  expected_value?: number;
  base_value?: number;
  tolerance?: number;
  unit?: string;
}

// Item response for the new phase-based flow
export interface ItemResponse {
  item_id: string;
  item_type: ItemType;
  // Values by type
  checkbox_value?: boolean;
  numeric_value?: number;
  text_value?: string;
  selection_value?: string;
  // Photo specific
  photo_url?: string;
  photo_verification_result?: "pass" | "fail" | "pending";
  photo_verification_message?: string;
  // Validation
  is_valid: boolean;
  validation_message?: string;
  // NG details - collected immediately when user selects No/fails validation
  ng_status?: NGStatus;
  ng_detail?: string;
}

// ==================== Updated Existing Models ====================

// Checklist item - updated for phase-based checkout
export interface CheckItem {
  id: string;
  topic: string;
  main_question: string;
  follow_up_hints: string[];
  item_type: ItemType;
  expected_answer?: "ok" | "ng";
  // Numeric validation
  numeric_validation?: NumericValidation;
  // Selection choices
  selection_choices?: string[];
  // Photo verification prompt
  verification_prompt?: string;
  // Display order
  order?: number;
  fixed_position?: number;
  // Legacy fields (kept for backward compatibility)
  priority: Priority;
  category: Category;
  is_required: boolean;
  needs_photo: boolean;
}

// Checklist template
export interface ChecklistTemplate {
  id: string;
  title: string;
  description: string;
  duration: number;
  items: CheckItem[];
  knowledge_context: string;
  randomize_order?: boolean;
  created_at: string;
  created_by: string;
  is_active: boolean;
}

// Checkout response (legacy - for conversation mode)
export interface CheckoutResponse {
  item_id: string;
  response_text: string;
  priority: Priority;
  status: CheckItemStatus;
  needs_followup: boolean;
  attachments: string[];
}

// Checkout session - updated for phase-based flow
export interface CheckoutSession {
  id: string;
  template_id: string;
  tenant_id?: string;
  operator_id: string;
  operator_name: string;
  next_operator_id?: string;
  next_operator_name: string;
  // New phase-based status
  status: SessionStatus;
  current_phase: number;
  // New phase-based responses
  item_responses: ItemResponse[];
  // Phase 3 settings
  ai_conversation_mode?: "chat" | "voice" | "voice_live";
  ng_item_ids: string[];
  // Phase 4 summary
  summary_markdown: string;
  summary_edited: boolean;
  // AI-generated action items (generated after Phase 3)
  action_items?: ActionItem[];
  // Phase timestamps
  phase1_completed_at?: string;
  phase2_completed_at?: string;
  phase3_completed_at?: string;
  // Legacy fields (kept for backward compatibility)
  current_item_id?: string;
  responses: CheckoutResponse[];
  parking_lot: string[];
  started_at: string;
  ended_at?: string;
}

// Extracted handover data
export interface ExtractedHandoverData {
  critical_items: string[];
  pending_tasks: string[];
  equipment_issues: string[];
  safety_notes: string[];
  general_notes: string[];
}

// Priority summary
export interface PrioritySummary {
  p0: number;
  p1: number;
  p2: number;
  p3: number;
}

// ==================== Action Items (AI-generated for next operator) ====================

// Action item dynamically generated by AI during checkout
export interface ActionItem {
  id: string;
  topic: string; // Action name (e.g., "2号炉の温度確認")
  description: string; // Detailed description
  item_type: ItemType; // checkbox / numeric / text / selection

  // Conditional action (optional)
  timing?: string; // When to do it (e.g., "17:00の巡回時")
  condition?: string; // Condition (e.g., "290℃以上なら")
  then_action?: string; // Action if condition met (e.g., "設備担当に連絡")

  // Evidence for transparency
  evidence?: string; // Original statement that triggered this action

  // Validation settings (same as CheckItem)
  numeric_validation?: NumericValidation;
  selection_choices?: string[];

  // Display order
  order?: number;
}

// Response/execution result for an action item by next operator
export interface ActionItemResponse {
  action_id: string;
  item_type: ItemType;
  // Values by type
  checkbox_value?: boolean;
  numeric_value?: number;
  text_value?: string;
  selection_value?: string;
  // Completion info
  note?: string; // Additional comment
  completed_at?: string;
  completed_by?: string;
  completed_by_name?: string;
}

// Handover note - updated with cancellation support
export interface HandoverNote {
  id: string;
  session_id: string;
  template_id: string;
  operator_id: string;
  operator_name: string;
  next_operator_id?: string;
  next_operator_name: string;
  summary_markdown: string;
  extracted_data: ExtractedHandoverData;
  is_confirmed: boolean;
  is_acknowledged?: boolean;
  confirmed_at?: string;
  created_at: string;
  priority_summary?: PrioritySummary;
  comments?: Comment[];
  // Admin cancellation support
  is_cancelled?: boolean;
  cancelled_at?: string;
  cancelled_by?: string;
  cancellation_reason?: string;
  // AI-generated action items for next operator
  action_items?: ActionItem[];
  action_responses?: ActionItemResponse[];
}

// Comment
export interface Comment {
  id: string;
  handover_id: string;
  author_id: string;
  author_name: string;
  content: string;
  created_at: string;
  is_resolved: boolean;
}

// Attachment
export interface Attachment {
  id: string;
  session_id: string;
  item_id: string;
  file_name: string;
  file_type: string;
  storage_url: string;
  thumbnail_url?: string;
  uploaded_at: string;
  uploaded_by: string;
}

// ==================== API Response types ====================

export interface StartCheckoutResponse {
  success: boolean;
  session_id: string;
  adk_session_id: string;
  message: string;
  quick_replies: string[];
}

export interface AudioResponse {
  audio_content: string; // base64 encoded
  audio_format: string;
  content_type: string;
}

export interface SendCheckoutMessageResponse {
  success: boolean;
  message: string;
  quick_replies: string[];
  is_complete: boolean;
  photo_request?: {
    description: string;
  };
  handover?: HandoverNote;
  transcription?: {
    text: string;
    confidence: number;
  };
  audio_response?: AudioResponse;
}

export interface VoiceGreetingResponse {
  success: boolean;
  message: string;
  audio_response?: AudioResponse;
}

export interface TemplateBuilderResponse {
  success: boolean;
  session_id: string;
  message: string;
  quick_replies: string[];
  template_created?: boolean;
  template?: ChecklistTemplate;
}

// ==================== New API Response types for Phase-based Checkout ====================

export interface Phase1SaveResponse {
  success: boolean;
  saved_count: number;
}

export interface PhaseCompleteResponse {
  success: boolean;
  next_phase: number;
  ng_items?: string[];
  summary?: string;
}

export interface PhotoUploadResponse {
  success: boolean;
  attachment_id: string;
  storage_url: string;
}

export interface PhotoVerifyResponse {
  success: boolean;
  result: "pass" | "fail" | "pending";
  message: string;
  error?: string;
}

export interface Phase3StartResponse {
  success: boolean;
  mode: "chat" | "voice";
}

export interface SessionCompleteResponse {
  success: boolean;
  handover: HandoverNote;
}

export interface SessionRestartResponse {
  success: boolean;
  message: string;
}

export interface CancelHandoverResponse {
  success: boolean;
  message: string;
}

// ==================== Inbox Types ====================

// Inbox item - notification for handover recipients
export interface InboxItem {
  id: string;
  handover_id: string;
  user_id: string;
  tenant_id?: string;
  // Handover info for display (denormalized)
  handover_title: string;
  operator_name: string;
  created_at: string;
  // Status
  is_read: boolean;
  is_deleted: boolean;
  read_at?: string;
  deleted_at?: string;
}

// Inbox list response
export interface InboxListResponse {
  items: InboxItem[];
  total: number;
}

// Inbox count response
export interface InboxCountResponse {
  count: number;
}

// Inbox filters
export interface InboxFilters {
  limit?: number;
  offset?: number;
  unread_only?: boolean;
}
