"""Data models for checklist and handover system."""

from enum import Enum
from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field


# ==================== New Enums for Phase-based Checkout ====================

class ItemType(str, Enum):
    """Check item type - determines which phase handles the item."""
    CHECKBOX = "checkbox"        # Yes/No check - Phase 1
    NUMERIC = "numeric"          # Numeric input with validation - Phase 1
    TEXT = "text"                # Text input - Phase 1
    SELECTION = "selection"      # Selection from choices - Phase 1
    PHOTO = "photo"              # Photo capture + AI verification - Phase 2
    # Note: ai_confirmation was removed - Phase 3 now always runs as final AI review


class NumericValidationType(str, Enum):
    """Numeric validation types."""
    MAX = "max"                  # Upper limit
    MIN = "min"                  # Lower limit
    RANGE = "range"              # Min-max range
    EXACT = "exact"              # Exact value
    TOLERANCE = "tolerance"      # Base value +/- tolerance


class SessionStatus(str, Enum):
    """Checkout session status - tracks which phase the session is in."""
    DRAFT = "draft"
    PHASE1 = "phase1"            # Form input phase
    PHASE2 = "phase2"            # Photo upload phase
    PHASE3 = "phase3"            # AI conversation phase
    PENDING_REVIEW = "pending_review"  # Summary review phase
    COMPLETED = "completed"
    ABANDONED = "abandoned"


class NGStatus(str, Enum):
    """Status for NG (problem) items."""
    UNRESOLVED = "unresolved"    # 未対処
    IN_PROGRESS = "in_progress"  # 対応中
    RESOLVED = "resolved"        # 対処済み


# ==================== Legacy Enums (kept for backward compatibility) ====================

class Priority(str, Enum):
    """Item priority levels (legacy - kept for migration)."""
    P0 = "P0"
    P1 = "P1"
    P2 = "P2"
    P3 = "P3"


class CheckItemStatus(str, Enum):
    """Check item completion status."""
    PENDING = "pending"
    DONE = "done"
    BLOCKED = "blocked"
    NA = "na"


class Category(str, Enum):
    """Checklist item categories (legacy - kept for migration)."""
    SAFETY = "safety"
    EQUIPMENT = "equipment"
    TASK = "task"
    HANDOVER = "handover"
    OTHER = "other"


# ==================== New Models for Phase-based Checkout ====================

class NumericValidation(BaseModel):
    """Numeric validation settings."""
    validation_type: NumericValidationType
    min_value: Optional[float] = None
    max_value: Optional[float] = None
    expected_value: Optional[float] = None
    base_value: Optional[float] = None
    tolerance: Optional[float] = None
    unit: str = ""  # e.g., "°C", "kg", "%"


class CheckItem(BaseModel):
    """Individual checklist item - updated for phase-based checkout."""
    id: str
    topic: str                                      # Item name
    main_question: str                              # Question text
    follow_up_hints: list[str] = Field(default_factory=list)
    item_type: ItemType = ItemType.CHECKBOX         # Item type
    expected_answer: str = "ok"                     # "ok" | "ng" - which answer is expected/correct
    # Numeric validation
    numeric_validation: Optional[NumericValidation] = None
    # Selection choices
    selection_choices: list[str] = Field(default_factory=list)
    # Photo verification prompt
    verification_prompt: str = ""                   # AI prompt for photo verification
    # Display order
    order: int = 0
    fixed_position: Optional[int] = None            # 1-indexed fixed position, None = randomize
    # Legacy fields (kept for backward compatibility during migration)
    priority: Priority = Priority.P2
    category: Category = Category.OTHER
    is_required: bool = True
    needs_photo: bool = False


class ItemResponse(BaseModel):
    """Response for a single check item in the new flow."""
    item_id: str
    item_type: ItemType
    # Values by type
    checkbox_value: Optional[bool] = None
    numeric_value: Optional[float] = None
    text_value: Optional[str] = None
    selection_value: Optional[str] = None
    # Photo specific
    photo_url: Optional[str] = None
    photo_verification_result: Optional[str] = None  # pass/fail/pending
    photo_verification_message: Optional[str] = None
    # Validation
    is_valid: bool = True
    validation_message: Optional[str] = None
    # NG details - collected immediately when user selects No/fails validation
    ng_status: Optional[NGStatus] = None  # 対処状況
    ng_detail: Optional[str] = None       # 詳細説明


# ==================== Action Items (AI-generated for next operator) ====================

class ActionItem(BaseModel):
    """Action item dynamically generated by AI during checkout.

    Uses the same item_type as CheckItem for consistency.
    Only generated when AI determines specific action is needed.
    """
    id: str
    topic: str                                      # Action name (e.g., "2号炉の温度確認")
    description: str                                # Detailed description
    item_type: ItemType = ItemType.CHECKBOX         # checkbox / numeric / text / selection

    # Conditional action (optional)
    timing: Optional[str] = None                    # When to do it (e.g., "17:00の巡回時")
    condition: Optional[str] = None                 # Condition (e.g., "290℃以上なら")
    then_action: Optional[str] = None               # Action if condition met (e.g., "設備担当に連絡")

    # Evidence for transparency
    evidence: str = ""                              # Original statement that triggered this action

    # Validation settings (same as CheckItem)
    numeric_validation: Optional[NumericValidation] = None
    selection_choices: list[str] = Field(default_factory=list)

    # Display order
    order: int = 0


# ==================== Existing Models (updated) ====================

class ChecklistTemplate(BaseModel):
    """Checklist template definition."""
    id: str
    title: str
    description: str
    duration: int = 600
    items: list[CheckItem] = Field(default_factory=list)
    knowledge_context: str = ""
    randomize_order: bool = False
    created_at: datetime = Field(default_factory=datetime.now)
    created_by: str = ""
    is_active: bool = True


class CheckoutResponse(BaseModel):
    """Response for a single check item (legacy - for conversation mode)."""
    item_id: str
    response_text: str
    priority: Priority = Priority.P2
    status: CheckItemStatus = CheckItemStatus.PENDING
    needs_followup: bool = False
    attachments: list[str] = Field(default_factory=list)


class CheckoutSession(BaseModel):
    """Active checkout session - updated for phase-based flow."""
    id: str
    template_id: str
    tenant_id: Optional[str] = None
    operator_id: str
    operator_name: str = ""
    next_operator_id: Optional[str] = None
    next_operator_name: str = ""
    # New phase-based status
    status: SessionStatus = SessionStatus.DRAFT
    current_phase: int = 1
    # New phase-based responses
    item_responses: list[ItemResponse] = Field(default_factory=list)
    # Phase 3 settings
    ai_conversation_mode: Optional[str] = None  # chat/voice
    ng_item_ids: list[str] = Field(default_factory=list)  # Items that failed validation
    # Phase 4 summary
    summary_markdown: str = ""
    summary_edited: bool = False
    # Phase timestamps
    phase1_completed_at: Optional[datetime] = None
    phase2_completed_at: Optional[datetime] = None
    phase3_completed_at: Optional[datetime] = None
    # Legacy fields (kept for backward compatibility)
    current_item_id: Optional[str] = None
    responses: list[CheckoutResponse] = Field(default_factory=list)
    parking_lot: list[str] = Field(default_factory=list)
    started_at: datetime = Field(default_factory=datetime.now)
    ended_at: Optional[datetime] = None
    # AI-generated action items (generated after Phase 3)
    action_items: list[ActionItem] = Field(default_factory=list)


class ExtractedHandoverData(BaseModel):
    """Structured data extracted from checkout."""
    critical_items: list[str] = Field(default_factory=list)
    pending_tasks: list[str] = Field(default_factory=list)
    equipment_issues: list[str] = Field(default_factory=list)
    safety_notes: list[str] = Field(default_factory=list)
    general_notes: list[str] = Field(default_factory=list)


class ActionItemResponse(BaseModel):
    """Response/execution result for an action item by next operator."""
    action_id: str
    item_type: ItemType
    # Values by type (same as ItemResponse)
    checkbox_value: Optional[bool] = None
    numeric_value: Optional[float] = None
    text_value: Optional[str] = None
    selection_value: Optional[str] = None
    # Completion info
    note: Optional[str] = None                      # Additional comment
    completed_at: Optional[datetime] = None
    completed_by: str = ""
    completed_by_name: str = ""


class HandoverNote(BaseModel):
    """Generated handover note - updated with cancellation support."""
    id: str
    session_id: str
    template_id: str
    operator_id: str
    operator_name: str
    next_operator_id: Optional[str] = None
    next_operator_name: str = ""
    summary_markdown: str = ""
    extracted_data: ExtractedHandoverData = Field(default_factory=ExtractedHandoverData)
    is_confirmed: bool = False
    confirmed_at: Optional[datetime] = None
    created_at: datetime = Field(default_factory=datetime.now)
    # New: Admin cancellation support
    is_cancelled: bool = False
    cancelled_at: Optional[datetime] = None
    cancelled_by: Optional[str] = None
    cancellation_reason: Optional[str] = None
    # New: AI-generated action items for next operator
    action_items: list[ActionItem] = Field(default_factory=list)
    action_responses: list[ActionItemResponse] = Field(default_factory=list)


class Comment(BaseModel):
    """Comment on a handover note."""
    id: str
    handover_id: str
    author_id: str
    author_name: str
    content: str
    created_at: datetime = Field(default_factory=datetime.now)
    is_resolved: bool = False


class Attachment(BaseModel):
    """File attachment metadata."""
    id: str
    session_id: str
    item_id: str
    file_name: str
    file_type: str
    storage_url: str
    thumbnail_url: Optional[str] = None
    uploaded_at: datetime = Field(default_factory=datetime.now)
    uploaded_by: str = ""


class InboxItem(BaseModel):
    """Inbox notification for handover recipients."""
    id: str
    handover_id: str
    user_id: str  # The recipient (next_operator_id)
    tenant_id: Optional[str] = None
    # Handover info for display (denormalized for performance)
    handover_title: str = ""
    operator_name: str = ""  # Who created the handover
    created_at: datetime = Field(default_factory=datetime.now)
    # Status
    is_read: bool = False
    is_deleted: bool = False  # Soft delete - removes from inbox but keeps handover
    read_at: Optional[datetime] = None
    deleted_at: Optional[datetime] = None
